### ISSUE TITLE
404 when accessing old job posts (due to caching?)

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/careers#101]
Reports from users – there are job post URLs 404ing upon access, even though the posts are long-existing.

Seems like this could be an issue with our bespoke caching of job posts: https://github.com/torchbox/careers/blob/main/pages/api/_peopleHR.ts

**Comment by Morsey187** [comment]
Just to clarify, I believe this has been fixed/resolved already as part of this PR #103 (see PR description), #104 is more of a tidy-up PR to reduce technical debt.

**Comment by Morsey187** [comment]
Resolving this issue based on testing #103 and the comment above
